    """
    This module contains the templates for the entities in the dataset. These
    templates are used by the NER pipeline.
    """

templates = {
    'PERSON': [
        "[PERSON] was seen at the location.",
        "Detective [PERSON] reviewed the case file.",
        "[PERSON] provided a crucial testimony.",
        "The statement was given by [PERSON].",
        "[PERSON] called for backup.",
        "Officer [PERSON] was on duty last night.",
        "[PERSON] signed the report.",
        "The warrant was issued to [PERSON].",
        "[PERSON] was promoted last week.",
        "Sergeant [PERSON] led the investigation.",
        "[PERSON] was last seen in the vicinity of the park.",
        "[PERSON]'s alibi was confirmed by two witnesses.",
        "The jury listened intently to [PERSON]'s testimony.",
        "[PERSON] was apprehended at the scene.",
        "[PERSON] has been a resident of the area for over a decade.",
        "During the interrogation, [PERSON] remained silent.",
        "[PERSON] was caught on the surveillance camera.",
        "The undercover operation involved [PERSON] as a key figure.",
        "[PERSON] is the lead detective on this case.",
        "[PERSON] testified that they had not seen anything unusual.",
        "The background check on [PERSON] came back clean.",
        "[PERSON] was the victim's associate.",
        "[PERSON] has been charged with multiple felonies.",
        "According to [PERSON], the event transpired rapidly.",
        "[PERSON] was granted immunity for their cooperation.",
        "The informant, [PERSON], provided vital information.",
        "[PERSON] is known to frequent the downtown area.",
        "Forensic analysis was requested by [PERSON].",
        "The defense attorney questioned [PERSON] relentlessly.",
        "[PERSON] oversees the forensic unit.",
        "[PERSON] filed a report on the incident last night.",
        "Backup was called by [PERSON] during the chase.",
        "[PERSON] was mentioned in the previous deposition.",
        "Neighborhood patrol was assigned to [PERSON].",
        "[PERSON] is under surveillance for suspicious activities.",
        "[PERSON]'s testimony contradicted the evidence.",
        "The search warrant was signed by [PERSON].",
        "[PERSON] participated in the lineup.",
        "Additional training was provided to [PERSON].",
        "[PERSON] was spotted near the crime scene shortly after.",
        "[PERSON] provided key insights during the investigation.",
        "[PERSON]'s whereabouts during the incident are unknown.",
        "The decision was ultimately made by [PERSON].",
        "[PERSON] was seen arguing with the suspect before the incident.",
        "[PERSON] called the emergency services immediately.",
        "[PERSON] has a history of similar allegations.",
        "The key witness in the case is [PERSON].",
        "[PERSON] is responsible for the forensic examination.",
        "The last communication was with [PERSON].",
        "Security footage shows [PERSON] leaving the building.",
        "[PERSON] was one of the last people to see the victim.",
        "[PERSON]'s fingerprints were found at the scene.",
        "The main suspect, identified as [PERSON], is still at large.",
        "[PERSON] has been placed under protective custody.",
        "Interviews with [PERSON] have yielded crucial clues.",
        "Officer [PERSON] responded to the emergency call.",
        "[PERSON] took the witness statement at the scene.",
        "Detective [PERSON] is leading the homicide investigation.",
        "Upon arrival, [PERSON] secured the perimeter.",
        "[PERSON] conducted a thorough search of the premises.",
        "During the pursuit, [PERSON] managed to apprehend the suspect.",
        "[PERSON] was in charge of evidence collection.",
        "Constable [PERSON] provided first aid to the injured party.",
        "[PERSON] interviewed the neighbors following the incident.",
        "[PERSON] reported the findings to the precinct.",
        "Sergeant [PERSON] briefed the team on the operation details.",
        "[PERSON] was recognized for exemplary service in the line of duty.",
        "Captain [PERSON] oversees the special task force.",
        "[PERSON] is coordinating with other agencies on the case.",
        "[PERSON] filed the arrest report.",
        "[PERSON] reviewed the surveillance footage for clues.",
        "[PERSON] is testifying at the trial.",
        "Commander [PERSON] approved the operation plan.",
        "[PERSON] is leading the interrogation of the prime suspect.",
        "Patrolman [PERSON] reported suspicious activity in the area.",
        "Officer [PERSON] secured the perimeter.",
        "[PERSON] radioed for immediate assistance.",
        "Detective [PERSON] interviewed the eyewitness.",
        "[PERSON] took notes at the crime scene.",
        "The report filed by [PERSON] was detailed.",
        "[PERSON] checked the vehicle's license plate.",
        "Sergeant [PERSON] led the briefing.",
        "[PERSON] was in charge of evidence collection.",
        "Lieutenant [PERSON] coordinated the response team.",
        "[PERSON] processed the arrest warrant.",
        "Constable [PERSON] patrolled the neighborhood.",
        "[PERSON] analyzed the surveillance footage.",
        "The undercover operation was led by [PERSON].",
        "[PERSON] testified at the trial.",
        "Captain [PERSON] reviewed the operation's success."
    ],
    'LOC': [
        "The event took place at [LOC].",
        "[LOC] was under surveillance.",
        "Evidence was collected at [LOC].",
        "The suspect fled towards [LOC].",
        "[LOC] is the primary crime scene.",
        "Backup was requested near [LOC].",
        "The operation covered the area around [LOC].",
        "A patrol car was stationed at [LOC].",
        "The briefing mentioned [LOC].",
        "Investigation expanded to include [LOC]."
        "A thorough search was conducted at [LOC].",
        "[LOC] is marked as a high-crime area.",
        "Additional units were dispatched to [LOC].",
        "The suspect was last seen heading towards [LOC].",
        "[LOC] has been cordoned off for further investigation.",
        "Forensic teams were deployed to [LOC].",
        "[LOC] is under the jurisdiction of the local precinct.",
        "Surveillance cameras at [LOC] captured the incident.",
        "All available units, please respond to [LOC].",
        "Detectives found crucial evidence at [LOC].",
        "The operation was centered around [LOC].",
        "Stakeout teams are positioned around [LOC].",
        "[LOC] was identified as the primary entry point.",
        "The rendezvous point was set at [LOC].",
        "[LOC] is known for its lack of surveillance.",
        "Patrols have been increased around [LOC].",
        "The tracking device was found discarded at [LOC].",
        "Helicopter support was requested above [LOC].",
        "[LOC] was mentioned during the briefing.",
        "The fugitive has been spotted in the vicinity of [LOC].",
        "Emergency services were directed to [LOC].",
        "All roads leading to [LOC] were blocked.",
        "[LOC] is considered a strategic vantage point.",
        "The command center is established near [LOC].",
        "Evacuation orders were issued for [LOC].",
        "[LOC] was secured by the SWAT team.",
        "[LOC] is a restricted access area.",
        "Intelligence suggests [LOC] is a key location.",
        "[LOC] is scheduled for demolition.",
        "Public access to [LOC] has been restricted.",
        "The incident was reported at [LOC], causing immediate response.",
        "Traffic was diverted away from [LOC] following the event.",
        "[LOC] is the main focus of the ongoing investigation.",
        "All witnesses were near [LOC] at the time of the incident.",
        "[LOC] is under constant surveillance due to recent threats.",
        "The evidence collected at [LOC] was pivotal for the case.",
        "Forensic teams concluded their examination at [LOC].",
        "Authorities are examining security footage from [LOC].",
        "The operation led to a significant discovery at [LOC].",
        "[LOC] is now considered a key point of interest.",
        "Emergency teams were quickly dispatched to [LOC].",
        "The press conference will be held outside [LOC].",
        "Several items were recovered from [LOC] for analysis.",
        "Law enforcement has established a perimeter around [LOC].",
        "Due to its significance, [LOC] will remain under guard.",
        "Patrols were increased near [LOC].",
        "[LOC] was identified as a hotspot for activity.",
        "The operation focused on the vicinity of [LOC].",
        "Evidence was last seen near [LOC].",
        "Surveillance operations expanded to [LOC].",
        "The command post was set up at [LOC].",
        "[LOC] was highlighted in the briefing.",
        "All units were directed to converge at [LOC].",
        "The search perimeter included [LOC].",
        "The suspect was last spotted near [LOC].",
        "Backup was requested at [LOC].",
        "Forensic teams scoured [LOC] for clues.",
        "[LOC] is under close watch for the next 24 hours.",
        "Security measures at [LOC] were heightened.",
        "The stakeout at [LOC] yielded crucial information."
    ]
}

validation_templates = {
    'PERSON': [
        "[PERSON] verified the suspect's alibi.",
        "[PERSON] obtained a search warrant from the judge.",
        "[PERSON] checked the vehicle's registration.",
        "[PERSON] is patrolling the high-risk neighborhood.",
        "[PERSON] attended the community meeting to discuss safety.",
        "[PERSON] was the victim's associate.",
        "[PERSON] has been charged with multiple felonies.",
        "According to [PERSON], the event transpired rapidly.",
        "[PERSON] was granted immunity for their cooperation.",
        "The informant, [PERSON], provided vital information.",
        "[PERSON] is known to frequent the downtown area.",
        "Forensic analysis was requested by [PERSON].",
        "The defense attorney questioned [PERSON] relentlessly.",
        "[PERSON] oversees the forensic unit.",
        "[PERSON] filed a report on the incident last night.",
        "Backup was called by [PERSON] during the chase.",
        "[PERSON] was mentioned in the previous deposition.",
        "Neighborhood patrol was assigned to [PERSON].",
        "[PERSON] is under surveillance for suspicious activities.",
        "[PERSON]'s testimony contradicted the evidence.",
        "The search warrant was signed by [PERSON].",
        "[PERSON] participated in the lineup.",
        "Additional training was provided to [PERSON].",
        "[PERSON] was spotted near the crime scene shortly after.",
        "[PERSON] provided key insights during the investigation.",
        "[PERSON] cross-referenced the database for leads.",
        "[PERSON] obtained a search warrant from the judge.",
        "The press conference was led by [PERSON].",
        "[PERSON] coordinated with federal agencies.",
        "The task force included Officer [PERSON].",
        "[PERSON] updated the victim's family.",
        "The crime scene log was maintained by [PERSON].",
        "[PERSON] canvassed the area for witnesses.",
        "Evidence tagging was overseen by [PERSON].",
        "[PERSON] dispatched units to the scene.",
        "Negotiations were handled by [PERSON].",
        "[PERSON] set up the roadblocks.",
        "The investigation's pace was set by [PERSON].",
        "[PERSON] liaised with the forensic team.",
        "The briefing notes were prepared by [PERSON].",
    ],
    'LOC': [
        "Backup was requested at the vicinity of [LOC].",
        "A hidden cache of weapons was discovered at [LOC].",
        "[LOC] was mentioned in the anonymous tip-off.",
        "Surveillance ops are active near [LOC].",
        "The patrol has been increased around [LOC].",
        "Surveillance cameras at [LOC] captured the incident.",
        "All available units, please respond to [LOC].",
        "Detectives found crucial evidence at [LOC].",
        "The operation was centered around [LOC].",
        "Stakeout teams are positioned around [LOC].",
        "[LOC] was identified as the primary entry point.",
        "The rendezvous point was set at [LOC].",
        "[LOC] is known for its lack of surveillance.",
        "Patrols have been increased around [LOC].",
        "The tracking device was found discarded at [LOC].",
        "Helicopter support was requested above [LOC].",
        "[LOC] was mentioned during the briefing.",
        "The fugitive has been spotted in the vicinity of [LOC].",
        "Emergency services were directed to [LOC].",
        "All roads leading to [LOC] were blocked.",
        "[LOC] is considered a strategic vantage point.",
        "The command center is established near [LOC].",
        "Evacuation orders were issued for [LOC].",
        "[LOC] was secured by the SWAT team.",
        "[LOC] is a restricted access area.",
        "Intelligence suggests [LOC] is a key location.",
        "[LOC] is scheduled for demolition.",
        "Public access to [LOC] has been restricted.",
        "The incident was reported at [LOC], causing immediate response.",
        "Traffic was diverted away from [LOC] following the event.",
        "[LOC] is the main focus of the ongoing investigation.",
        "All witnesses were near [LOC] at the time of the incident.",
        "[LOC] is under constant surveillance due to recent threats.",
        "The evidence collected at [LOC] was pivotal for the case.",
        "Forensic teams concluded their examination at [LOC].",
        "Authorities are examining security footage from [LOC].",
        "The operation led to a significant discovery at [LOC].",
        "A new lead pointed towards [LOC].",
        "The community outreach program was launched at [LOC].",
        "[LOC] was mapped for the upcoming patrol.",
        "The tactical unit assembled at [LOC].",
        "An anonymous tip mentioned [LOC].",
        "[LOC] became a focal point of the investigation.",
        "A surveillance drone was deployed over [LOC].",
        "The public was advised to avoid [LOC].",
        "Key evidence was traced back to [LOC].",
        "The media gathered outside [LOC].",
        "Logistical support was based out of [LOC].",
        "The K-9 unit was active around [LOC].",
        "A witness reported suspicious activity at [LOC].",
        "The operation's success depended on intel from [LOC].",
        "Emergency response teams were dispatched to [LOC]."
    ]
}

testing_templates = {
    'PERSON': [
        "[PERSON] was seen at the location.",
        "Detective [PERSON] reviewed the case file.",
        "[PERSON] provided a crucial testimony.",
        "The statement was given by [PERSON].",
        "[PERSON] called for backup.",
        "Officer [PERSON] was on duty last night.",
        "[PERSON] signed the report.",
        "The warrant was issued to [PERSON].",
        "[PERSON] was promoted last week.",
        "Sergeant [PERSON] led the investigation.",
        "[PERSON] was last seen in the vicinity of the park.",
        "[PERSON]'s alibi was confirmed by two witnesses.",
        "The jury listened intently to [PERSON]'s testimony.",
        "[PERSON] was apprehended at the scene.",
        "[PERSON] has been a resident of the area for over a decade.",
        "During the interrogation, [PERSON] remained silent.",
        "[PERSON] was caught on the surveillance camera.",
        "The undercover operation involved [PERSON] as a key figure.",
        "[PERSON] is the lead detective on this case.",
        "[PERSON] testified that they had not seen anything unusual.",
        "The background check on [PERSON] came back clean.",
        "[PERSON] was the victim's associate.",
        "[PERSON] has been charged with multiple felonies.",
        "According to [PERSON], the event transpired rapidly.",
        "[PERSON] was granted immunity for their cooperation.",
        "The informant, [PERSON], provided vital information.",
        "[PERSON] is known to frequent the downtown area.",
        "Forensic analysis was requested by [PERSON].",
        "The defense attorney questioned [PERSON] relentlessly.",
        "[PERSON] oversees the forensic unit.",
        "[PERSON] filed a report on the incident last night.",
        "Backup was called by [PERSON] during the chase.",
        "[PERSON] was mentioned in the previous deposition.",
        "Neighborhood patrol was assigned to [PERSON].",
        "[PERSON] is under surveillance for suspicious activities.",
        "[PERSON]'s testimony contradicted the evidence.",
        "The search warrant was signed by [PERSON].",
        "[PERSON] participated in the lineup.",
        "Additional training was provided to [PERSON].",
        "[PERSON] was spotted near the crime scene shortly after."
        "[PERSON] is analyzing the forensic evidence.",
        "[PERSON] escorted the witness to safety.",
        "[PERSON] is negotiating with the hostage takers.",
        "[PERSON] placed the roadblock near the crime scene.",
        "[PERSON] is reviewing the criminal profiles.",
        "[PERSON] checked in with the command center.",
        "The strategic plan was approved by [PERSON].",
        "[PERSON] organized the evidence locker.",
        "The night shift report was filed by [PERSON].",
        "[PERSON] was assigned to the surveillance team.",
        "The forensic analysis confirmed [PERSON]'s theory.",
        "Community relations were bolstered by [PERSON].",
        "[PERSON] managed the incident database.",
        "The new protocol was implemented by [PERSON].",
        "[PERSON] attended the interagency meeting.",
        "The training seminar was conducted by [PERSON].",
        "Crime statistics were compiled by [PERSON].",
    ],
    'LOC': [
        "[LOC] was under surveillance.",
        "Evidence was collected at [LOC].",
        "The suspect fled towards [LOC].",
        "[LOC] is the primary crime scene.",
        "Backup was requested near [LOC].",
        "The operation covered the area around [LOC].",
        "A patrol car was stationed at [LOC].",
        "The briefing mentioned [LOC].",
        "Investigation expanded to include [LOC]."
        "A thorough search was conducted at [LOC].",
        "[LOC] is marked as a high-crime area.",
        "Additional units were dispatched to [LOC].",
        "The suspect was last seen heading towards [LOC].",
        "[LOC] has been cordoned off for further investigation.",
        "Forensic teams were deployed to [LOC].",
        "[LOC] is under the jurisdiction of the local precinct.",
        "Surveillance cameras at [LOC] captured the incident.",
        "All available units, please respond to [LOC].",
        "Detectives found crucial evidence at [LOC].",
        "The stakeout is in place at [LOC].",
        "Evidence of arson was found at [LOC].",
        "[LOC] is the last known location of the suspect.",
        "The command post is set up at [LOC].",
        "Reinforcements headed towards [LOC].",
        "The incident was reported at [LOC], causing immediate response.",
        "Traffic was diverted away from [LOC] following the event.",
        "[LOC] is the main focus of the ongoing investigation.",
        "All witnesses were near [LOC] at the time of the incident.",
        "[LOC] is under constant surveillance due to recent threats.",
        "The evidence collected at [LOC] was pivotal for the case.",
        "Forensic teams concluded their examination at [LOC].",
        "Authorities are examining security footage from [LOC].",
        "The operation led to a significant discovery at [LOC].",
        "[LOC] is now considered a key point of interest.",
    ]
}